### ISSUE TITLE
Transmission build

### ISSUE THREAD

**Issue by Madseason41** [petersendev/hassio-addons#65]
There have been changes to this build, some of which are required for PIA to work. Any chance you are going to update the script to use the latest release? For PIA, I do know required changes were pulled into the master about a day ago, but a new release was not created. Not sure if that affects things?

https://github.com/haugene/docker-transmission-openvpn/commit/cc66a953493884b5ae02aa43ab6fa115b38234ad

Thanks!

**Comment by petersendev** [comment]
My addon is still on the 2.x version since they changed a lot.
I am in no rush to upgrade since everything is working for me.
If I see more demand I'll expedite, just vote up)

You could always use your own openvpn config file (hassio config folder: transmission-openpvn/openvpn/PROVIDERNAME/SERVER.ovpn - don't use existing provider name) and configure like this:

```yaml
OPENVPN_PROVIDER: PROVIDERNAME
OPENVPN_CONFIG: SERVER
OPENVPN_USERNAME: XXXX
OPENVPN_PASSWORD: YYYY
```
